archs:
  - ppc64le
  - x86_64

distributions:
  - el7

release_branches:
  master:
    - ovirt-master
  ovirt-4.2:
    - ovirt-4.2

stages:
  - build-artifacts
  - check-patch:
      archs:
        - x86_64
